### ISSUE TITLE
Biblatex for AIP style

### ISSUE THREAD

**Issue by Servinjesus1** [compholio/csm-thesis#1]
I'm having an issue using BibLaTeX to compile the bibliography, which I would like to use to have access to `style=phys` to match the AIP citation style (since I'm a physics major). It seems like `csm-thesis` is still trying to enforce bibtex customizations, which throw two errors:

`Required section (environment) missing: bibliography. \end{document}`
`Package biblatex Error: '\bibliographystyle' invalid. \end{document}`

On Overleaf, these issues are ignored and the document compiles regardless, however locally (I use TeXStudio w/ MikTex on Windows 10), this halts the compilation.

I've tried modifying the `latex-traditional-example` document to confirm that this what's causing the issue, as well as run a complete MWE with solely biblatex to confirm it's not my compiler. Specifically, all I added was:

```latex
%\usepackage[numbers]{natbib}
\usepackage[%
    backend=biber,
    style=phys,
    citestyle=numeric,
    maxbibnames=5,
    natbib=true,
    url=false,
    backref=true
]{biblatex}
\addbibresource{thesis}
```

commenting out natbib in favor of biblatex, using the same example `thesis.bib` and, of course, changing `\bibliography{thesis}` to `\printbibliography`.

**Comment by compholio** [comment]
At some point I broke biblatex compatibility when I forced compliance with the OGS bibliography style requirements.  I have disabled this style override when using biblatex (so please make sure that you use a style that OGS will accept), but your issue should now be fixed.  Please also remember to add the .bib extension when using biblatex:
```
\addbibresource{thesis.bib}
```
