### ISSUE TITLE
Extra \endgroup error

### ISSUE THREAD

**Issue by LodewijkBrand** [compholio/csm-thesis#4]
I was having some trouble compiling the `.tex` associated with this work using `pdflatex`. 

I'm not exactly sure what caused the error but.. removing lines

https://github.com/compholio/csm-thesis/blob/77c85b13111d0b50fd7592762ff9792da64ae673/csm-thesis-sanity.sty#L72

and

https://github.com/compholio/csm-thesis/blob/77c85b13111d0b50fd7592762ff9792da64ae673/csm-thesis-sanity.sty#L76

fixed the problem.

**Comment by compholio** [comment]
I suspect that this is something that is failing with the new latex hook mechanism. ( ran into that with another package: https://github.com/compholio/jabbrv/issues/27#issuecomment-795006694 )

Would you please create a document with this command in it and tell me what version (YYYY-MM-DD) you get?:
```
\fmtversion
```

**Comment by LodewijkBrand** [comment]
When I create a document with `\fmtversion` I get: 2020-10-01

**Comment by compholio** [comment]
Try replacing:
```
\global\let\orig@begin@document=\document
\gdef\document{%
	\endgroup
	\let\CSM@AtEndPreamble\@firstofone%
	\csm@endpreamblehook%
	\global\let\csm@endpreamblehook\@empty%
	\begingroup
	\orig@begin@document%
	\let\CSM@AtBeginDocumentLast\@firstofone%
	\csm@begindocumenthook%
	\global\let\csm@begindocumenthook\@empty%
}
```
with:
```
\RequirePackage{etoolbox}
\AtEndPreamble{%
	\let\CSM@AtEndPreamble\@firstofone%
	\csm@endpreamblehook%
	\global\let\csm@endpreamblehook\@empty%
}
\AfterEndPreamble{%
	\let\CSM@AtBeginDocumentLast\@firstofone%
	\csm@begindocumenthook%
	\global\let\csm@begindocumenthook\@empty%
}
```

**Comment by LodewijkBrand** [comment]
That worked! Thank you for for your efforts on the template!

**Comment by compholio** [comment]
> That worked! Thank you for for your efforts on the template!

No problem, happy to help!
